services:
  dpsrv-envoy:
    container_name: dpsrv-envoy-${tag:-latest}
    image: dpsrv/envoy:${tag:-latest}
    build: .
    env_file:
      - ${DPSRV_HOME}/rc/secrets/envoy/envoy.env
      - ${DPSRV_HOME}/rc/secrets/local/${HOSTNAME}/local.env
    ports:
      - "50180:80"
      - "50543:443"
    volumes:
      - ${DPSRV_HOME}/rc/secrets/envoy/envoy.yaml:/etc/envoy/envoy.yaml2:ro
      - ${DPSRV_HOME}/rc/secrets/letsencrypt/:/etc/letsencrypt/:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
